=== haldyr/psimulator/telnet-a-shell/src/data/psimulator.dtd
<!-- <?xml version="1.0" encoding="UTF-8" ?> -->
<!-- http://www.hitsw.com/xml_utilites/ -->

<!ELEMENT access-list ( cislo, ipA, ipAWildcard ) >

<!ELEMENT access-listy ( access-list+ ) >

<!ELEMENT accessCislo ( #PCDATA ) >

<!ELEMENT adresat ( #PCDATA ) >

<!ELEMENT brana ( #PCDATA ) >

<!ELEMENT cislo ( #PCDATA ) >

<!ELEMENT ip ( #PCDATA ) >

<!ELEMENT ipA ( #PCDATA ) >

<!ELEMENT ipAWildcard ( #PCDATA ) >

<!ELEMENT ip_forward ( #PCDATA ) >

<!ELEMENT ip_konec ( #PCDATA ) >

<!ELEMENT ip_start ( #PCDATA ) >

<!ELEMENT jmeno ( #PCDATA ) >

<!ELEMENT konfigurak ( pocitac+, kabelaz ) >

<!ELEMENT kabelaz ( kabel+ ) >

<!ELEMENT kabel ( prvni, druhy ) >

<!ELEMENT prvni ( #PCDATA ) >

<!ELEMENT druhy ( #PCDATA ) >

<!ELEMENT mac ( #PCDATA ) >

<!ELEMENT maska ( #PCDATA ) >

<!ELEMENT maskaAdresata ( #PCDATA ) >

<!ELEMENT nahozene ( #PCDATA ) >

<!ELEMENT nat ( #PCDATA ) >

<!ELEMENT natovani ( pooly, prirazeniVice, access-listy, staticke? ) >

<!ELEMENT staticke ( in, out ) >

<!ELEMENT in ( #PCDATA ) >

<!ELEMENT out ( #PCDATA ) >

<!ELEMENT overload ( #PCDATA ) >

<!ELEMENT pJmeno ( #PCDATA ) >

<!ELEMENT pocitac ( rozhrani+, routy, ip_forward?, natovani? ) >
<!ATTLIST pocitac jmeno NMTOKEN #REQUIRED >
<!ATTLIST pocitac typ NMTOKEN #REQUIRED >

<!ELEMENT pool ( pJmeno, ip_start, ip_konec, prefix ) >

<!ELEMENT poolJmeno ( #PCDATA ) >

<!ELEMENT pooly ( pool+ ) >

<!ELEMENT port ( #PCDATA ) >

<!ELEMENT prefix ( #PCDATA ) >

<!ELEMENT pripojenoK ( #PCDATA ) >

<!ELEMENT prirazeni ( accessCislo, poolJmeno, overload ) >

<!ELEMENT prirazeniVice ( prirazeni+ ) >

<!ELEMENT routy ( zaznam? ) >

<!ELEMENT rozhrani ( jmeno, ip, maska, mac, pripojenoK, nahozene, nat? ) >

<!ELEMENT rozhraniKam ( #PCDATA ) >

<!ELEMENT zaznam ( adresat, maskaAdresata, rozhraniKam, brana? ) >

=== haldyr/psimulator/src/data/psi2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD tady musi byt!!! -->
<!DOCTYPE konfigurak SYSTEM "psimulator.dtd">

<konfigurak>
<pocitac jmeno="linux1" typ="linux">
	<rozhrani>
		<jmeno>eth1</jmeno>
		<ip>1.1.1.2</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:05</mac>
		<pripojenoK>cisco1:FastEthernet0/0</pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>1.1.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>0</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

<pocitac jmeno="cisco1" typ="cisco">
	<rozhrani>
		<jmeno>FastEthernet0/0</jmeno>
		<ip>1.1.1.254</ip>
		<maska>255.255.255.0</maska>
		<mac>00:0b:0c:0d:0a:01</mac>
		<pripojenoK>linux1:eth1</pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<rozhrani>
		<jmeno>FastEthernet0/1</jmeno>
		<ip>2.2.2.1</ip>
		<maska>255.255.255.0</maska>
		<mac>03:08:b7:30:24:e1</mac>
		<pripojenoK>cisco2:FastEthernet0/0</pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
	</routy>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

<pocitac jmeno="cisco2" typ="cisco">
	<rozhrani>
		<jmeno>FastEthernet0/0</jmeno>
		<ip>2.2.2.254</ip>
		<maska>255.255.255.0</maska>
		<mac>00:0b:0c:0d:0a:01</mac>
		<pripojenoK>cisco1:FastEthernet0/1</pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>1.1.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<brana>2.2.2.0</brana>
		</zaznam>
	</routy>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

<kabelaz>
	<kabel>
		<prvni>linux1:eth1</prvni>
		<druhy>cisco1:FastEthernet0/0</druhy>
	</kabel>
	<kabel>
		<prvni>cisco1:FastEthernet0/1</prvni>
		<druhy>cisco2:FastEthernet0/0</druhy>
	</kabel>
</kabelaz>
</konfigurak>

=== haldyr/psimulator/src/data/linDefProtiSobe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD tady musi byt!!! -->
<!DOCTYPE konfigurak SYSTEM "psimulator.dtd">

<konfigurak>
<pocitac jmeno="linux1" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.1.1</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:05</mac>
		<pripojenoK>linux2:eth0</pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.1.2</brana>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>0</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

<pocitac jmeno="linux2" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.1.2</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:06</mac>
		<pripojenoK>linux1:eth0</pripojenoK>
		<nahozene>true</nahozene>
		<nat>soukrome</nat>
	</rozhrani>
	<rozhrani>
		<jmeno>eth1</jmeno>
		<ip>192.168.2.1</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:d3:04:06</mac>
		<pripojenoK>linux3:eth0</pripojenoK>
		<nahozene>true</nahozene>
		<nat>verejne</nat>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>192.168.2.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.2.2</brana>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>1</ip_forward>
	<natovani>
		<pooly>
			<pool>
				<pJmeno>ovrld</pJmeno>
				<ip_start>192.168.2.1</ip_start>
				<ip_konec>192.168.2.1</ip_konec>
				<prefix>24</prefix>
			</pool>
		</pooly>
		<prirazeniVice>
			<prirazeni>
				<accessCislo>1</accessCislo>
				<poolJmeno>ovrld</poolJmeno>
				<overload>true</overload>
			</prirazeni>
		</prirazeniVice>
		<access-listy>
			<access-list>
				<cislo>1</cislo>
				<ipA>0.0.0.0</ipA>
				<ipAWildcard>255.255.255.255</ipAWildcard>
			</access-list>
		</access-listy>
	</natovani>
</pocitac>

<pocitac jmeno="linux3" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.2.2</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:07</mac>
		<pripojenoK>linux2:eth1</pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<rozhrani>
		<jmeno>eth1</jmeno>
		<ip></ip>
		<maska></maska>
		<mac>00:01:02:03:0a:07</mac>
		<pripojenoK></pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.2.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.2.1</brana>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>1</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

<kabelaz>
	<kabel>
		<prvni>linux1:eth0</prvni>
		<druhy>linux2:eth0</druhy>
	</kabel>
	<kabel>
		<prvni>linux2:eth1</prvni>
		<druhy>linux3:eth0</druhy>
	</kabel>
</kabelaz>
</konfigurak>

=== haldyr/psimulator/src/data/testovani.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD tady musi byt!!! -->
<!DOCTYPE konfigurak SYSTEM "psimulator.dtd">

<konfigurak>
<pocitac jmeno="linux1" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.1.1</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:05</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.1.2</brana>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>0</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac
>
<pocitac jmeno="linux2" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.1.2</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:05</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<rozhrani>
		<jmeno>eth1</jmeno>
		<ip>192.168.2.1</ip>
		<maska>255.255.255.192</maska>
		<mac>00:01:02:03:04:05</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.2.0</adresat>
			<maskaAdresata>255.255.255.192</maskaAdresata>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.2.2</brana>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>1</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac
>
<pocitac jmeno="cisco1" typ="cisco">
	<rozhrani>
		<jmeno>FastEthernet0/0</jmeno>
		<ip>192.168.2.2</ip>
		<maska>255.255.255.192</maska>
		<mac>00:0b:0c:0d:0a:01</mac>
		<nahozene>true</nahozene>
		<nat>soukrome</nat>
	</rozhrani>
	<rozhrani>
		<jmeno>FastEthernet0/1</jmeno>
		<ip>10.0.0.1</ip>
		<maska>255.255.255.248</maska>
		<mac>03:08:b7:30:24:e1</mac>
		<nahozene>true</nahozene>
		<nat>verejne</nat>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<brana>192.168.2.1</brana>
		</zaznam>
	</routy>
	<natovani>
		<pooly>
			<pool>
				<pJmeno>o1</pJmeno>
				<ip_start>10.0.0.5</ip_start>
				<ip_konec>10.0.0.5</ip_konec>
				<prefix>24</prefix>
			</pool>
			<pool>
				<pJmeno>o2</pJmeno>
				<ip_start>10.0.0.77</ip_start>
				<ip_konec>10.0.0.80</ip_konec>
				<prefix>24</prefix>
			</pool>
		</pooly>
		<prirazeniVice>
			<prirazeni>
				<accessCislo>7</accessCislo>
				<poolJmeno>o1</poolJmeno>
				<overload>true</overload>
			</prirazeni>
		</prirazeniVice>
		<access-listy>
			<access-list>
				<cislo>7</cislo>
				<ipA>192.168.2.1</ipA>
				<ipAWildcard>0.0.0.3</ipAWildcard>
			</access-list>
		</access-listy>
		<staticke>
			<in>192.168.1.1</in>
			<out>10.0.0.6</out>
		</staticke>
	</natovani>
</pocitac
>
<pocitac jmeno="cisco2" typ="cisco">
	<rozhrani>
		<jmeno>FastEthernet0/0</jmeno>
		<ip>10.0.0.2</ip>
		<maska>255.255.255.248</maska>
		<mac>00:0b:0c:0d:0a:01</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<rozhrani>
		<jmeno>FastEthernet0/1</jmeno>
		<ip>147.32.125.129</ip>
		<maska>255.255.255.128</maska>
		<mac>00:0b:0c:0d:0a:10</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
	</routy>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac
>
<kabelaz>
	<kabel>
		<prvni>linux1:eth0</prvni>
		<druhy>linux2:eth0</druhy>
	</kabel>
	<kabel>
		<prvni>linux2:eth1</prvni>
		<druhy>cisco1:FastEthernet0/0</druhy>
	</kabel>
	<kabel>
		<prvni>cisco1:FastEthernet0/1</prvni>
		<druhy>cisco2:FastEthernet0/0</druhy>
	</kabel>
</kabelaz>
</konfigurak>

=== haldyr/psimulator/src/data/linDoZtracena.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD tady musi byt!!! -->
<!DOCTYPE konfigurak SYSTEM "psimulator.dtd">

<konfigurak>
<pocitac jmeno="linux1" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.1.1</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:05</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.1.2</brana>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>0</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

<pocitac jmeno="linux2" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.1.2</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:06</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<rozhrani>
		<jmeno>eth1</jmeno>
		<ip>192.168.2.1</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:d3:04:06</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>192.168.2.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.2.2</brana>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>1</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

<pocitac jmeno="linux3" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.2.2</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:07</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<rozhrani>
		<jmeno>eth1</jmeno>
		<ip>10.0.0.1</ip>
		<maska>255.0.0.0</maska>
		<mac>00:01:02:03:0a:07</mac>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.2.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<brana>192.168.2.1</brana>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>10.0.0.0</adresat>
			<maskaAdresata>255.0.0.0</maskaAdresata>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>10.0.0.2</brana>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>1</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

<kabelaz>
	<kabel>
		<prvni>linux1:eth0</prvni>
		<druhy>linux2:eth0</druhy>
	</kabel>
	<kabel>
		<prvni>linux2:eth1</prvni>
		<druhy>linux3:eth0</druhy>
	</kabel>
</kabelaz>
</konfigurak>
